accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # 회원가입
    path("signup/", views.signup, name="signup"),
    # 로그인
    path("login/", views.login, name="login"),
    # 로그아웃
    path("logout/", views.logout, name="logout"),
    # 회원탈퇴
    path("delete_user/", views.delete_user, name="delete_user"),
    # 메인화면
    path("", views.main, name="main"),
    # 마이페이지
    path("mypage/", views.mypage_view, name="mypage"),
    # 마이페이지 수정
    path("edit_mypage", views.edit_mypage, name="edit_mypage"),
    # 비밀번호 변경
    path("password_change/", views.password_change, name="password_change"),
    # 비밀번호 변경 완료 화면
    path(
        "password_change/done/", views.password_change_done, name="password_change_done"
    ),
    # 아이디 찾기
    path("find_id/", views.find_id, name="find_id"),
    # 비밀번호 찾기(초기화)
    path("password_reset/", views.password_reset, name="password_reset"),
    # 비밀번호 초기화 메일 발송 완료 화면
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    # 새 비밀번호 설정 완료
    path(
        "reset/<uidb64>/<token>/",
        views.password_reset_confirm,
        name="password_reset_confirm",
    ),
]

chatbot/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "chatbot"

urlpatterns = [
    # 챗봇 url
    path("", views.chatbot, name="chatbot"),
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name="accounts/main.html"), name="main"),
]

mysite/urls.py
import debug_toolbar
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls", namespace="accounts")),
    path("team/", include("team.urls")),
    path("core/", include("core.urls")),
    path("chatbot/", include("chatbot.urls", namespace="chatbot")),
]

if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    # 이미지 파일 경로 받기
    # static 함수는 settings의 debug설정이 참일때만 동작함
    # static은 개발편의성을 위해 정적파일 서빙 기능을 제공

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

team/urls.py
from django.urls import path
from . import views

# from .views import MessageListCreateAPIView

app_name = "team"
urlpatterns = [
    # 마이팀 누르면 팀생성하기 또는 팀 가입하기 보여주기
    path("myteam/", views.myteam, name="myteam"),
    path("myteam/<int:team_id>/", views.myteam, name="team_dashboard"),
    # 팀 생성하기
    path("create_team/", views.create_team, name="create_team"),
    # 팀프로필 수정
    path(
        "update_team_profile/<int:pk>/",
        views.update_team_profile,
        name="update_team_profile",
    ),
    # 팀 가입하기 누르면 팀들 나오고 가입하기까지
    path("team_list/", views.team_list, name="team_list"),
    path("join_team/<int:team_id>/", views.join_team, name="join_team"),
    # 생성된 경기들 보여주기
    path("matches/", views.match_list, name="match_list"),
    # 경기 생성하기
    path("matches/create/", views.create_match, name="create_match"),
    # 경기 참여하기
    path("matches/join/<int:match_id>/", views.join_match, name="join_match"),
    # 경기 리포트 작성
    path(
        "match_report/<int:team_id>/",
        views.create_match_result,
        name="match_report",
    ),
    # 경기 리포트 수정
    path(
        "match_report_edit/<int:result_id>/",
        views.edit_match_result,
        name="match_report_edit",
    ),
    # 팀 경기 일정
    path("match_schedule/", views.match_schedule, name="match_schedule"),
    # 팀 스토리
    path("team_story/", views.team_story, name="team_story"),
    # path("chat/<int:team_id>/", views.team_chat, name="team_chat"),
    # path(
    #     "api/messages/<int:team_id>/",
    #     MessageListCreateAPIView.as_view(),
    #     name="message-list-create",
    # ),
    # 팀 경기 영상 분석
    path("video_analysis/<int:team_id>/", views.video_analysis, name="video_analysis"),
    # 영상분석 시작 버튼
    # path(
    #     "analyze_video/<int:match_id>/",
    #     views.analyze_video,
    #     name="analyze_video",
    # ),
    # 팀 탈퇴
    path("leave_team/", views.leave_team, name="leave_team"),
    # 팀 삭제
    path("delete_team/", views.delete_team, name="delete_team"),
    # 게시판 리스트 url
    path("board/<int:team_id>/", views.board_list, name="board_list"),
    # 게시글 생성
    path("board/<int:team_id>/create/", views.board_create, name="board_create"),
    # 게시글 목록
    path("board/<int:team_id>/<int:pk>/", views.board_detail, name="board_detail"),
    # 게시글 수정
    path(
        "board/<int:team_id>/<int:pk>/update/", views.board_update, name="board_update"
    ),
    # 게시글 삭제
    path(
        "board/<int:team_id>/<int:pk>/delete/", views.board_delete, name="board_delete"
    ),
    # 댓글 삭제
    path(
        "board/<int:team_id>/<int:pk>/comment_delete/",
        views.board_comment_delete,
        name="board_comment_delete",
    ),
    # 댓글 업데이트
    path(
        "board/<int:team_id>/<int:pk>/comment_update/",
        views.board_comment_update,
        name="board_comment_update",
    ),
    # path(
    #     "video_analysis/<int:team_id>/result/",
    #     views.analysis_result_basic,
    #     name="analysis_result_basic",
    # ),
    # 영상분석에서 영상분석결과 이미지 경로 전달
    path("viz/<path:path>", views.serve_image, name="serve_image"),
    # path("<path:path>", views.serve_image, name="serve_image"),
]

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/_crispy_form.html
{% load crispy_forms_tags %}
{% load static %}

<div class="row py-5">
    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-10 offset-sm-1">
        <div class="card">
            {% if form_title %}
                <div class="card-header">
                    {{ form_title }}
                </div>
            {% endif %}
            <div class="card-body">
                {% if form.helper %}
                    {% crispy form form.helper %}
                {% else %}
                    {% crispy form %}
                {% endif %}
                <div class="text-center mt-3">
                    <a href="{% url 'accounts:find_id' %}" class="btn btn-link">아이디 찾기</a>
                    <a href="{% url 'accounts:password_reset' %}" class="btn btn-link">비밀번호 찾기</a>
                </div>
            </div>
        </div>
    </div>
</div>

{# 메타데이터 #}
<div id="metadata-popup" class="metadata-popup">
    <span class="close">&times;</span>
    <h2>축구 수준의 종류</h2>
    <p>풋린이가 가장 낮은 수준, 풋롱도르가 가장 높은 수준이에요.</p>
    <ul>
        <li><strong>풋린이(Beginner)</strong> 풋살을 처음 시작한 단계로, 기본적인 풋살 기술에 익숙하지 않은 실력을 갖고 있어요.</li>
        <li><strong>풋내기(Novice)</strong> 몇 차례의 풋살 게임을 경험한 정도로, 약간의 경험은 있지만 아직 미숙한 수준이에요.</li>
        <li><strong>풋아마(Amateur)</strong> 꾸준히 풋살을 즐기며 기본 기술을 익힌 중간 수준의 단계에요. 기본적인 기술을 보유하고 있지만 아직 발전의 여지가 많아요.</li>
        <li><strong>풋현역(Intermediate)</strong> 많은 풋살 게임 경험이 있고 전술적인 이해도가 높아요. 다양한 기술을 보유하고 있으며 팀원들과의 협업도 원활해요.</li>
        <li><strong>풋롱도르(Expert)</strong> 가장 뛰어난 수준으로 전문적인 기술과 팀원들과의 완벽한 협업을 자랑해요. 전략적이고 창의적인 플레이에 능숙하며, 리더십이 뛰어난 분들이에요.</li>
    </ul>
</div>

<!-- 팝업을 위한 CSS -->
<style>
    .metadata-popup {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: white;
        border: 1px solid #ccc;
        padding: 20px;
        z-index: 1000;
    }
    .metadata-popup .close {
        cursor: pointer;
        color: red;
    }
</style>

<!-- 팝업을 위한 JavaScript -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    var infoIcon = document.getElementById('info-icon');
    if (infoIcon) {
        var popup = document.getElementById('metadata-popup');
        var closeBtn = document.querySelector('.metadata-popup .close');

        infoIcon.addEventListener('click', function() {
            popup.style.display = 'block';
        });

        closeBtn.addEventListener('click', function() {
            popup.style.display = 'none';
        });

        window.addEventListener('click', function(event) {
            if (event.target == popup) {
                popup.style.display = 'none';
            }
        });
    }
});
</script>

core/templates/_messages_as_event.html
{% if messages %}
    {% for message in messages %}
        <script>
          (function () {
            const tag = "{{ message.level_tag }}";
            const message = "{{ message }}"
            /* body 요소에 toast-message 이벤트를 보냅니다. */
            htmx.trigger(document.body, 'toast-message', {message: message, tag: tag});
          })();
        </script>
    {% endfor %}
{% endif %}

core/templates/base.html
{% load component_tags static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Football Agora</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}"/>
    <link href='https://unpkg.com/fullcalendar@5.3.1/main.min.css' rel='stylesheet' />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@400;700&family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">

    <style>

    {#<script src='https://unpkg.com/fullcalendar@5.3.1/main.min.js'></script>#}
    {#<style>#}
        .cute-font {
            font-family: 'Comic Neue', 'Noto Sans KR', sans-serif !important;
        }

        .nav-pills {
            display: flex;
            justify-content: center;
            width: 100%;
        }
        .nav-pills .nav-item {
            flex: 1;
            text-align: center;
        }
        .nav-pills .nav-link {
            color: black;
            font-size: 1.5rem; /* 글자 크기 조정 */
            font-family: inherit; /* 부모 요소의 글씨체 상속 */
        }
        .nav-pills .nav-link:hover {
            color: black;
        }

        .navbar-item {
            position: relative;
            padding: 10px;
            display: flex;
            align-items: center; /* 높이 맞추기 */
        }

        .navbar-item .dropdown-menu {
            display: none;
            position: absolute;
            top: 40px;
            left: 0;
            background-color: white;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            z-index: 1;
        }

        .navbar-item:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu a {
            display: block;
            padding: 10px;
            color: black !important;
            text-decoration: none;
            white-space: nowrap;
        }

        .dropdown-menu a:hover {
            background-color: #f0f0f0;
            color: black !important;
        }

        .dropdown-toggle::after {
            display: none;
        }

        .profile-container {
            display: flex;
            align-items: center;
            position: relative;
        }

        .profile-container span {
            margin-right: 10px; /* 사용자 이름과 이미지 사이에 여백 추가 */
        }

        .profile-container img {
            margin-left: 5px;
            cursor: pointer;
        }

        .profile-buttons {
            display: flex;
            align-items: center;
        }

        .profile-buttons a {
            margin-left: 10px; /* 버튼들 사이에 여백 추가 */
        }

        .list-group-item {
            border: 1px solid #ddd;
            border-radius: 0.25rem;
            margin-bottom: 10px;
            transition: background-color 0.2s ease-in-out;
        }

        .list-group-item:hover {
            background-color: #f8f9fa;
        }

        .list-group-item .fa-2x {
            color: #007bff;
        }

        .card-header {
            background-color: #f8f9fa;
        }

        .card-header .btn-close {
            font-size: 1.25rem;
            padding: 0.5rem;
            cursor: pointer;
        }

        .card-footer .btn-warning {
            background-color: #ffc107;
            border-color: #ffc107;
        }

        .card-footer .btn-warning:hover {
            background-color: #e0a800;
            border-color: #d39e00;
        }

        .banner {
            position: relative;
            text-align: center;
            color: white;
        }

        .banner img {
            width: 100%;
            height: 400px;
        }

        .banner .slogan {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 2rem;
            background-color: rgba(0, 0, 0, 0.5);
            padding: 10px 20px;
            border-radius: 5px;
        }

        /* 검정색 상단 바 길이 조정 */
        header.p-3.text-bg-dark {
            height: 100px; /* 바 높이를 늘립니다. 필요에 따라 높이를 조정하세요 */
            display: flex;
            align-items: center;
        }

        /* 상단 바 안의 글씨 크기 조정 */
        header.p-3.text-bg-dark a,
        header.p-3.text-bg-dark .profile-container span,
        header.p-3.text-bg-dark .profile-buttons a {
            font-size: 20px; /* 글씨 크기를 늘립니다. 필요에 따라 크기를 조정하세요 */
            color: snow; /* 글씨 색상을 흰색으로 유지합니다 */
        }


    </style>
    {% component_css_dependencies %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' class="cute-font">

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FootballAgora
            </a>

            <div class="text-end">
                {% if not user.is_authenticated %}
                    {% url 'accounts:login' as login_url %}
                    <a href="{{ login_url }}{% if login_url != request.path %}?next={{ request.path }}{% endif %}" class="btn btn-outline-light me-2">로그인</a>
                    <a href="{% url 'accounts:signup' %}?next={{ request.path }}" class="btn btn-warning">회원가입</a>
                {% else %}
                    <div class="profile-container">
                        <span>{{ user.username }}님</span>
                        <div class="dropdown">
                            <img src="{% static 'images/soccer_ball.png' %}" alt="Profile" width="30" height="30" class="dropdown-toggle" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                                <li><a href="{% url 'accounts:mypage' %}" class="dropdown-item">My Page</a></li>
                                <li><a href="{% url 'team:myteam' %}" class="dropdown-item">My Team</a></li>
                            </ul>
                        </div>
                        <div class="profile-buttons">
                            <a hx-post="{% url 'accounts:logout' %}?next={% url 'accounts:main' %}" hx-target="body" hx-push-url="true" class="btn btn-warning">로그아웃</a>
                            <a href="{% url 'accounts:password_change' %}" class="btn btn-warning">비밀번호 변경</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</header>



<main class="py-5">
    <div class="container">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
{#                <li class="nav-item navbar-item"><a href="#" class="nav-link" aria-current="page">풋살장 예약</a></li>#}
                <li class="nav-item navbar-item">
                    <a href="#" class="nav-link">FA TEAM</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'team:team_story' %}">Team Story</a>
                        <a href="{% url 'team:match_list' %}">Team Match</a>
                        <a href="{% url 'team:myteam' %}">My Team</a>
                    </div>
                </li>
                <li class="nav-item navbar-item"><a href="{% url 'chatbot:chatbot' %}" class="nav-link">Chatbot</a></li>
            </ul>
        </header>
         {% block banner %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
    </div>
</footer>
{% if debug %}
    <script src="{% static 'htmx/1.9.11/htmx.js' %}"></script>
{% else %}
    <script src="{% static 'htmx/1.9.11/htmx.min.js' %}"></script>
{% endif %}
<script src="{% static 'bootstrap/5.3.3/js/bootstrap.bundle.min.js' %}"></script>
{% component_js_dependencies %}
<script src="{% static 'htmx/ext/ hx-get-with-timestamp.js' %}"></script>
<script src="{% static 'toast-messages.js' %}"></script>

{% include "_messages_as_event.html" %}

</body>
</html>

core/templates/crispy_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "_crispy_form.html" with form=form form_title=form_title %}
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

<script>
document.addEventListener('DOMContentLoaded', function() {
    var teamImageUrl = document.getElementById('id_team_image_url');
    if (teamImageUrl) {
        teamImageUrl.onchange = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('team_image_preview');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        };
    }
});
</script>