core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name="accounts/main.html"), name="main"),
]

team/urls.py
from django.urls import path
from . import views

# from .views import MessageListCreateAPIView

app_name = "team"
urlpatterns = [
    # 마이팀 누르면 팀생성하기 또는 팀 가입하기 보여주기
    path("myteam/", views.myteam, name="myteam"),
    path("myteam/<int:team_id>/", views.myteam, name="team_dashboard"),
    # 팀 생성하기
    path("create_team/", views.create_team, name="create_team"),
    # 팀프로필 수정
    path(
        "update_team_profile/<int:pk>/",
        views.update_team_profile,
        name="update_team_profile",
    ),
    # 팀 가입하기 누르면 팀들 나오고 가입하기까지
    path("team_list/", views.team_list, name="team_list"),
    path("join_team/<int:team_id>/", views.join_team, name="join_team"),
    # 생성된 경기들 보여주기
    path("matches/", views.match_list, name="match_list"),
    # 경기 생성하기
    path("matches/create/", views.create_match, name="create_match"),
    # 경기 참여하기
    path("matches/join/<int:match_id>/", views.join_match, name="join_match"),
    # 경기 리포트 작성
    path(
        "match_report/<int:team_id>/",
        views.create_match_result,
        name="match_report",
    ),
    # 경기 리포트 수정
    path(
        "match_report_edit/<int:result_id>/",
        views.edit_match_result,
        name="match_report_edit",
    ),
    # 팀 경기 일정
    path("match_schedule/", views.match_schedule, name="match_schedule"),
    # 팀 스토리
    path("team_story/", views.team_story, name="team_story"),
    # path("chat/<int:team_id>/", views.team_chat, name="team_chat"),
    # path(
    #     "api/messages/<int:team_id>/",
    #     MessageListCreateAPIView.as_view(),
    #     name="message-list-create",
    # ),
    # 팀 경기 영상 분석
    path("video_analysis/<int:team_id>/", views.video_analysis, name="video_analysis"),
    # 영상분석 시작 버튼
    # path(
    #     "analyze_video/<int:match_id>/",
    #     views.analyze_video,
    #     name="analyze_video",
    # ),
    # 팀 탈퇴
    path("leave_team/", views.leave_team, name="leave_team"),
    # 팀 삭제
    path("delete_team/", views.delete_team, name="delete_team"),
    # 게시판 리스트 url
    path("board/<int:team_id>/", views.board_list, name="board_list"),
    # 게시글 생성
    path("board/<int:team_id>/create/", views.board_create, name="board_create"),
    # 게시글 목록
    path("board/<int:team_id>/<int:pk>/", views.board_detail, name="board_detail"),
    # 게시글 수정
    path(
        "board/<int:team_id>/<int:pk>/update/", views.board_update, name="board_update"
    ),
    # 게시글 삭제
    path(
        "board/<int:team_id>/<int:pk>/delete/", views.board_delete, name="board_delete"
    ),
    # 댓글 삭제
    path(
        "board/<int:team_id>/<int:pk>/comment_delete/",
        views.board_comment_delete,
        name="board_comment_delete",
    ),
    # 댓글 업데이트
    path(
        "board/<int:team_id>/<int:pk>/comment_update/",
        views.board_comment_update,
        name="board_comment_update",
    ),
    # path(
    #     "video_analysis/<int:team_id>/result/",
    #     views.analysis_result_basic,
    #     name="analysis_result_basic",
    # ),
    # 영상분석에서 영상분석결과 이미지 경로 전달
    path("viz/<path:path>", views.serve_image, name="serve_image"),
    # path("<path:path>", views.serve_image, name="serve_image"),
]

team/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import Group


class Court(models.Model):
    # 경기장 정보
    court_no = models.PositiveSmallIntegerField(primary_key=True)
    court_name = models.CharField(max_length=50)
    court_address = models.CharField(max_length=100)
    sido_name = models.CharField(max_length=10)
    sigg_name = models.CharField(max_length=10)
    number_3vs3 = models.TextField(
        db_column="3vs3"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_4vs4 = models.TextField(
        db_column="4vs4"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_5vs5 = models.TextField(
        db_column="5vs5"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_6vs6 = models.TextField(
        db_column="6vs6"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_7vs7 = models.TextField(
        db_column="7vs7"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_8vs8 = models.TextField(
        db_column="8vs8"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_9vs9 = models.TextField(
        db_column="9vs9"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.
    number_11vs11 = models.TextField(
        db_column="11vs11"
    )  # Field renamed because it wasn't a valid Python identifier. This field type is a guess.

    # 기타 시설 정보
    cool_heating = models.TextField()  # This field type is a guess.
    cooling = models.TextField()  # This field type is a guess.
    team_vest = models.TextField()  # This field type is a guess.
    training_zone = models.TextField()  # This field type is a guess.
    rent_balls = models.TextField()  # This field type is a guess.
    rent_shoes = models.TextField()  # This field type is a guess.
    shower_room = models.TextField()  # This field type is a guess.
    parking = models.TextField()  # This field type is a guess.

    class Meta:
        managed = False
        db_table = "court"


class Team(models.Model):
    team_no = models.AutoField(primary_key=True)
    team_name = models.CharField(unique=True, max_length=10)
    team_image_url = models.ImageField(
        upload_to="teams/images/%Y/%m/%d/", blank=True, null=True
    )
    team_day = models.CharField(max_length=15)
    team_timeslot = models.CharField(max_length=10)
    team_ages = models.CharField(max_length=10)

    # 팀 성별 선택
    GENDER_CHOICES = [
        ("여성", "여성"),
        ("남성", "남성"),
        ("혼성", "혼성"),
    ]
    gender = models.CharField(
        max_length=2, choices=GENDER_CHOICES, null=True, blank=True
    )
    team_level = models.IntegerField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)

    # 팀 멤버
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="teams", blank=True
    )
    # 팀장 지정
    created_by = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name="created_team", on_delete=models.CASCADE
    )
    sido_name = models.CharField(max_length=10)
    sigg_name = models.CharField(max_length=10)
    court_name = models.CharField(max_length=50)

    # 경기 기록
    match_count = models.PositiveIntegerField(default=0)
    win_count = models.PositiveIntegerField(default=0)
    draw_count = models.PositiveIntegerField(default=0)
    lose_count = models.PositiveIntegerField(default=0)
    goal_difference = models.IntegerField(default=0)
    points = models.PositiveIntegerField(default=0)

    class Meta:
        managed = True
        db_table = "team"

    def __str__(self):
        return self.team_name

    def get_members_usernames(self):
        return ", ".join([member.username for member in self.members.all()])

    def is_leader(self, user):
        return self.created_by == user

    def delete(self, *args, **kwargs):
        # 팀 삭제 시 members 필드를 비워야 합니다.
        self.members.clear()
        super().delete(*args, **kwargs)


# 팀 채팅 메시지
# class Message(models.Model):
#     team = models.ForeignKey(
#         "team.Team", related_name="messages", on_delete=models.CASCADE
#     )
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     content = models.TextField()
#     timestamp = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return f"{self.user.username}: {self.content[:20]}"


# 팀 매치
class Match(models.Model):
    team = models.ForeignKey(
        "team.Team",
        on_delete=models.SET_NULL,
        null=True,
        related_name="matches",
    )
    team_vs = models.ForeignKey(
        "team.Team",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="applied_matches",
    )
    date = models.DateField()
    time = models.TimeField()
    sido_name = models.CharField(max_length=10)
    sigg_name = models.CharField(max_length=10)
    court_name = models.CharField(max_length=50)

    # 매치 성별 선택
    GENDER_CHOICES = [
        ("여성", "여성"),
        ("남성", "남성"),
        ("혼성", "혼성"),
    ]
    gender = models.CharField(
        max_length=2, choices=GENDER_CHOICES, null=True, blank=True
    )
    members_count = models.PositiveIntegerField()
    level = models.CharField(max_length=4)
    status = models.CharField(max_length=10, default="모집중")

    def __str__(self):
        return f"{self.team} - {self.date} {self.time} at {self.court_name}"

    def join_match(self, team):
        if self.team_vs is None:
            self.team_vs = team
            self.status = "모집 마감"
            self.save()
            return True
        return False


# 경기 결과
class MatchResult(models.Model):
    team = models.ForeignKey(
        "team.Team",
        related_name="results",
        on_delete=models.SET_NULL,
        null=True,
    )
    opponent = models.ForeignKey(
        "team.Team",
        related_name="opponent_results",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    date = models.DateField()
    result = models.CharField(
        max_length=1, choices=[("W", "Win"), ("D", "Draw"), ("L", "Lose")]
    )
    # 득점
    goals_for = models.IntegerField()
    # 실점
    goals_against = models.IntegerField()

    # 비디오파일 업로드
    video_file_left = models.FileField(
        upload_to="analysis/files/%Y/%m/%d/left/", null=True, blank=True
    )
    video_file_right = models.FileField(
        upload_to="analysis/files/%Y/%m/%d/right/", null=True, blank=True
    )

    # 경기 리포트 작성한 사람
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="match_results", on_delete=models.CASCADE
    )

    # 경기 참여한 멤버들
    players = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="match_results_players", blank=True
    )

    class Meta:
        ordering = ["date"]

    @property
    def goal_difference(self):
        return self.goals_for - self.goals_against

    @property
    def points(self):
        if self.result == "W":
            return 3
        elif self.result == "D":
            return 1
        else:
            return 0

    def __str__(self):
        return f"{self.team.team_name} vs {self.opponent.team_name} on {self.date}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        update_team_ranking(self.team)
        update_opponent_ranking(self)

        # Create or update the opponent's MatchResult


# 팀 순위 갱신
def update_team_ranking(team):
    team_results = team.results.all()
    match_count = team_results.count()
    win_count = team_results.filter(result="W").count()
    draw_count = team_results.filter(result="D").count()
    lose_count = team_results.filter(result="L").count()
    goal_difference = sum(result.goal_difference for result in team_results)
    points = sum(result.points for result in team_results)

    team.match_count = match_count
    team.win_count = win_count
    team.draw_count = draw_count
    team.lose_count = lose_count
    team.goal_difference = goal_difference
    team.points = points
    team.save()


# 상대팀 순위 갱신
def update_opponent_ranking(match_result):
    opponent_results = MatchResult.objects.filter(team=match_result.opponent)
    match_count = opponent_results.count()
    win_count = opponent_results.filter(result="W").count()
    draw_count = opponent_results.filter(result="D").count()
    lose_count = opponent_results.filter(result="L").count()
    goal_difference = sum(result.goal_difference for result in opponent_results)
    points = sum(result.points for result in opponent_results)

    opponent = match_result.opponent
    opponent.match_count = match_count
    opponent.win_count = win_count
    opponent.draw_count = draw_count
    opponent.lose_count = lose_count
    opponent.goal_difference = goal_difference
    opponent.points = points
    opponent.save()


# *관계 : 기본 User - Teamboard - BoardComment
# 게시판 클래스
class Teamboard(models.Model):
    team = models.ForeignKey(
        "team.Team", on_delete=models.CASCADE, related_name="boards"
    )
    # User 기본 테이블에 사용자가 지워지면 Post 데이터도 지워짐. 1(User):N(Teamboard)관계
    createUser = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    boardTitle = models.CharField(max_length=50)  # 게시글 제목
    boardContent = models.TextField()  # 게시글 내용
    boardImg = models.ImageField(
        upload_to="board/images/%Y/%m/%d/", blank=True, null=True
    )  # 첨부파일
    createDate = models.DateTimeField(auto_now_add=True)  # 등록일
    updateDate = models.DateField(auto_now=True)  # 수정일
    viewCnt = models.IntegerField(default=0)  # 조회수
    commentCnt = models.IntegerField(default=0)  # 댓글수

    def __str__(self):
        return f"{self.pk}번째 등록글 : {self.boardTitle} (등록일 : {self.createDate})"

team/templates/access_denied.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>접근 권한이 없습니다</h1>
        <p>이 페이지에 접근할 권한이 없습니다. 팀 멤버만 접근할 수 있습니다.</p>
        <a href="{% url 'myteam' %}" class="btn btn-primary">마이 페이지로 돌아가기</a>
    </div>
</body>
</html>

team/templates/create_match.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>경기 생성</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">경기 생성</button>
    </form>
</div>
{% endblock %}

team/templates/create_match_result.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2>경기 리포트 작성</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_date" class="form-label">경기 날짜:</label>
                    {{ form.date }}
                </div>
                <div class="mb-3">
                    <label for="id_opponent" class="form-label">상대 팀:</label>
                    {{ form.opponent }}
                </div>
                <div class="mb-3">
                    <label for="id_result" class="form-label">결과 입력:</label>
                    {{ form.result }}
                </div>
                <div class="mb-3">
                    <label for="id_goals_for" class="form-label">득점:</label>
                    {{ form.goals_for }}
                </div>
                <div class="mb-3">
                    <label for="id_goals_against" class="form-label">실점:</label>
                    {{ form.goals_against }}
                </div>

                <div class="mb-3">
                    <label for="id_video_file_left" class="form-label">왼쪽 비디오 파일:</label>
                    {{ form.video_file_left }}
                </div>

                <div class="mb-3">
                    <label for="id_video_file_right" class="form-label">오른쪽 비디오 파일:</label>
                    {{ form.video_file_right }}
                </div>
                <button type="submit" class="btn btn-primary">저장</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

team/templates/create_team.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h2>팀 생성하기</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_team_name" class="form-label">팀의 이름을 정해주세요</label>
            <p class="form-text">팀을 대표하는 멋진 이름을 지어주세요!</p>
            {{ form.team_name }}
        </div>

        <div class="mb-3">
            <label class="form-label">팀 대표 이미지를 골라주세요</label>
            {% if form.team_image_url.value %}
                <img id="team_image_preview" src="{{ form.team_image_url.value.url }}" alt="Team Image Preview" class="img-thumbnail" style="max-width: 150px;">
            {% else %}
                <img id="team_image_preview" src="{% static 'images/normal_image.png' %}" alt="Default Team Image" class="img-thumbnail" style="max-width: 150px;">
            {% endif %}
            {{ form.team_image_url }}
        </div>

        <div class="mb-3">
            <label class="form-label">팀의 주 활동 시간을 입력해주세요</label>
            <p class="form-text">활동 요일 (중복 선택 가능)</p>
            {{ form.team_day }}
        </div>

        <div class="mb-3">
            <p class="form-text">주 활동시간대 (택1)</p>
            {{ form.team_timeslot }}
        </div>

        <div class="mb-3">
            <label class="form-label">주로 활동하는 지역과 구장을 선택해주세요</label>
            <div class="row">
                <div class="col-md-4">
                    <label for="id_sido_name">도시</label>
                    {{ form.sido_name }}
                </div>
                <div class="col-md-4">
                    <label for="id_sigg_name">지역구</label>
                    {{ form.sigg_name }}
                </div>
                <div class="col-md-4">
                    <label for="id_ground">주 활동 구장</label>
                    {{ form.court_name }}
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label class="form-label">팀의 나이대와 성별을 알려주세요</label>
            <div class="row">
                <div class="col-md-6">
                    <p class="form-text">주요 나이대 (택1)</p>
                    {{ form.team_ages }}
                </div>
                <div class="col-md-6">
                    <p class="form-text">성별 (택1)</p>
                    {{ form.gender }}
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">팀 생성하기</button>
    </form>
</div>

<script>
document.getElementById('id_team_image_url').onchange = function (event) {
    var reader = new FileReader();
    reader.onload = function () {
        var output = document.getElementById('team_image_preview');
        output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
};
</script>
{% endblock %}

team/templates/match_list.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>경기 목록</h2>
    <div class="row">
        {% for match in matches %}
            <div class="col-md-4 mb-3">
                <div class="card">
                     <div class="card-body">
                        <h5 class="card-title">경기생성팀 이름: {{ match.team.team_name }}</h5>
                        <p class="card-text">일자: {{ match.date }} {{ match.time }}</p>
                        <p class="card-text">장소: {{ match.court_name }}</p>
                        <p class="card-text">성별: {{ match.gender }}</p>
                        <p class="card-text">인원: {{ match.members_count }}명</p>
                        <p class="card-text">수준: {{ match.level }}</p>
                        <p class="card-text">모집 현황: {{ match.status }}</p>
                        {% if match.status != "모집 마감" and match.team_vs is None and user.team_no and user.team_no.created_by == user %}
                            <form action="{% url 'team:join_match' match.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">경기 참여</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="text-end">
        {% if user.team_no and user.team_no.created_by == user %}
            <a href="{% url 'team:create_match' %}" class="btn btn-primary">경기 생성</a>
        {% endif %}
    </div>
</div>

<!-- 메시지를 표시할 영역 -->
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

team/templates/result.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>분석 결과</h2>
    <img src="{{ result_image }}" alt="분석 결과 이미지" class="img-fluid">
    <a href="{% url 'team:video_analysis' match_result.team.team_no %}" class="btn btn-secondary mt-3">다시 분석하기</a>
</div>
{% endblock %}

team/templates/team_create_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="modal-title">메뉴는 팀에 소속되어 있는 회원만 이용할 수 있어요</h5>
            <button type="button" class="btn-close" aria-label="Close" onclick="window.location.href='/'"></button>
        </div>
        <div class="card-body">
            <div class="list-group">
                <a href="{% url 'team:create_team' %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="fas fa-users-cog fa-2x me-3"></i>
                            <h5 class="mb-1">팀 생성하기</h5>
                        </div>
                    </div>
                    <p class="mb-1">회원님만의 팀을 생성하고 팀원을 모집하세요!</p>
                </a>
                <a href="{% url 'team:team_list' %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <div class="d-flex align-items-center">
                            <i class="fas fa-user-plus fa-2x me-3"></i>
                            <h5 class="mb-1">팀 가입하기</h5>
                        </div>
                    </div>
                    <p class="mb-1">회원님의 맘에 쏙 드는 팀을 찾아 보세요!</p>
                </a>
            </div>
        </div>
        <div class="card-footer text-end">
            <button type="button" class="btn btn-warning" onclick="window.location.href='/'">취소</button>
        </div>
    </div>
</div>
{% endblock %}

team/templates/team_dashboard.html
{% extends "base.html" %}
{% load static %}
{% load age_filter %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center">
        <h2>팀 프로필 <span style="color: orange;">{{ team.team_name }}</span></h2>
        <div>
            {% if user == team.created_by %}
                <a href="{% url 'team:update_team_profile' team.pk %}" class="btn btn-primary me-2">팀 프로필 수정</a>
            {% endif %}
            <a href="{% url 'team:match_report' team.team_no %}" class="btn btn-primary me-2">경기 리포트 작성</a>
            {% if match_results %}
                <a href="{% url 'team:match_report_edit' match_results.first.id %}" class="btn btn-primary me-2">경기 리포트 수정</a>
            {% else %}
                <span class="btn btn-primary me-2 disabled">경기 리포트 수정</span>
            {% endif %}
            <a href="{% url 'team:board_list' team.team_no %}" class="btn btn-primary me-2">팀 게시판</a>
            <a href="{% url 'team:video_analysis' team.team_no %}" class="btn btn-primary me-2">영상 분석</a>
            <a href="{% url 'team:match_schedule' %}" class="btn btn-secondary">나의 팀 경기일정</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            {% if team.team_image_url %}
                <img src="{{ team.team_image_url.url }}" alt="팀 이미지" class="img-thumbnail" style="max-width: 150px;">
            {% else %}
                <img src="{% static 'images/normal_image.png' %}" alt="기본 팀 이미지" class="img-thumbnail" style="max-width: 150px;">
            {% endif %}
        </div>
        <div class="col-md-9">
            <p>인원: {{ team.members.count }}명</p>
            <p>팀 성별: {{ team.gender }}</p>
            <p>팀 평균 연령대: {{ team.team_ages }}</p>
            <p>주 활동 구장: {{ team.court_name }}</p>
        </div>
    </div>

    <h3 class="mt-4">팀 순위</h3>
    <table class="table">
        <thead>
            <tr>
                <th>순위</th>
                <th>팀 이름</th>
                <th>경기</th>
                <th>승</th>
                <th>무</th>
                <th>패</th>
                <th>골득실</th>
                <th>승점</th>
            </tr>
        </thead>
        <tbody>
            {% for ranking in team_rankings %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ ranking.team.team_name }}</td>
                <td>{{ ranking.match_count }}</td>
                <td>{{ ranking.win_count }}</td>
                <td>{{ ranking.draw_count }}</td>
                <td>{{ ranking.lose_count }}</td>
                <td>{{ ranking.goal_difference }}</td>
                <td>{{ ranking.points }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3 class="mt-4">멤버 구성</h3>
    <div class="row">
        {% for member in team.members.all %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body d-flex align-items-center">
                        <div class="flex-shrink-0">
                            {% if member.image_url %}
                                <img src="{{ member.image_url.url }}" alt="프로필 이미지" class="img-thumbnail" style="max-width: 50px;">
                            {% else %}
                                <img src="{% static 'images/normal_image.png' %}" alt="기본 프로필 이미지" class="img-thumbnail" style="max-width: 50px;">
                            {% endif %}
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <p class="mb-1"><strong>이름:</strong> {{ member.username }}</p>
                            <p class="mb-1"><strong>성별:</strong> {{ member.gender }}</p>
                            <p class="mb-1"><strong>연령:</strong> {{ member.birth_date|age }}</p>
                            <p class="mb-1"><strong>포지션:</strong> {{ member.position_1 }}</p>
                            {% if team.created_by == member %}
                                <p class="mb-1"><strong>팀장</strong></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if user == team.created_by %}
        {% if team.members.count == 1 %}
            <form action="{% url 'team:delete_team' %}" method="post" class="mt-4">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">팀 삭제</button>
            </form>
        {% endif %}
    {% else %}
        <form action="{% url 'team:leave_team' %}" method="post" class="mt-4">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning">팀 탈퇴</button>
        </form>
    {% endif %}

</div>
{% endblock %}

team/templates/update_match_result.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h2>경기 결과 수정</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_date" class="form-label">경기 날짜:</label>
                    {{ form.date }}
                </div>
                <div class="mb-3">
                    <label for="id_opponent" class="form-label">상대 팀:</label>
                    {{ form.opponent }}
                </div>
                <div class="mb-3">
                    <label for="id_result" class="form-label">결과 입력:</label>
                    {{ form.result }}
                </div>
                <div class="mb-3">
                    <label for="id_goals_for" class="form-label">득점:</label>
                    {{ form.goals_for }}
                </div>
                <div class="mb-3">
                    <label for="id_goals_against" class="form-label">실점:</label>
                    {{ form.goals_against }}
                </div>
                 <div class="mb-3">
                    <label for="id_video_file_left" class="form-label">왼쪽 비디오 파일:</label>
                    {{ form.video_file_left }}
                </div>
                <div class="mb-3">
                    <label for="id_video_file_right" class="form-label">오른쪽 비디오 파일:</label>
                    {{ form.video_file_right }}
                </div>
                <button type="submit" class="btn btn-primary">저장</button>
            </form>
            <form method="post" class="mt-3">
                {% csrf_token %}
                <button type="submit" name="delete" class="btn btn-danger">경기 리포트 삭제</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}